//Variables para el API REST
const API_URL = process.env.REACT_APP_API_URL;
const API_PUERTO = process.env.REACT_APP_PUERTO;
const API_DONAS_GUARDAR = process.env.REACT_APP_API_DONAS_GUARDAR;
const API_DONAS_OBTENER = process.env.REACT_APP_API_DONAS_OBTENER;
const API_USUARIOS_BUSCAR_NOMBRE =
  process.env.REACT_APP_API_USUARIOS_BUSCAR_NOMBRE;
const API_USUARIOS_GUARDAR = process.env.REACT_APP_API_USUARIOS_GUARDAR;
const API_USUARIOS_VERIFICAR = process.env.REACT_APP_API_USUARIOS_VERIFICAR;
const API_USUARIOS_ACTUALIZAR_CONEXION =
  process.env.REACT_APP_API_USUARIOS_ACTUALIZAR_CONEXION;

export {
  API_URL,
  API_PUERTO,
  API_DONAS_GUARDAR,
  API_DONAS_OBTENER,
  API_USUARIOS_BUSCAR_NOMBRE,
  API_USUARIOS_GUARDAR,
  API_USUARIOS_VERIFICAR,
  API_USUARIOS_ACTUALIZAR_CONEXION,
};
